In [7]:
import numpy as np
import pandas as pd

In [8]:
# open udays_badpWeights.npy

uday_weights = np.load('pk_badpWeights.npy')

In [9]:
# open matlab_badpWeights.npy

matlab_weights = np.load('matlab_badpWeights.npy')

In [10]:
uday_weights

array([[0.23234782, 0.02109773, 0.08111183, ..., 0.        , 0.        ,
        0.        ],
       [0.21137909, 0.02109767, 0.08106224, ..., 0.        , 0.        ,
        0.        ],
       [0.2066114 , 0.02109605, 0.08098712, ..., 0.        , 0.        ,
        0.        ],
       [0.00167742, 0.02089991, 0.00193446, ..., 0.        , 0.        ,
        0.        ],
       [0.00161188, 0.        , 0.00181638, ..., 0.        , 0.        ,
        0.        ]])

In [11]:
matlab_weights

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
weightT = matlab_weights.T
weightT

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
df = pd.DataFrame(weightT)

In [16]:
df

0    1    2    3    4
0    0.0  0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0  0.0
..   ...  ...  ...  ...  ...
835  0.0  0.0  0.0  0.0  0.0
836  0.0  0.0  0.0  0.0  0.0
837  0.0  0.0  0.0  0.0  0.0
838  0.0  0.0  0.0  0.0  0.0
839  0.0  0.0  0.0  0.0  0.0

[840 rows x 5 columns]

In [18]:
uday_weights
r_weights = np.round(uday_weights.copy(),0)
r_weights

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
df_r = pd.DataFrame(r_weights.T)
df_r

0    1    2    3    4
0    0.0  0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0  0.0
..   ...  ...  ...  ...  ...
835  0.0  0.0  0.0  0.0  0.0
836  0.0  0.0  0.0  0.0  0.0
837  0.0  0.0  0.0  0.0  0.0
838  0.0  0.0  0.0  0.0  0.0
839  0.0  0.0  0.0  0.0  0.0

[840 rows x 5 columns]

In [20]:
df_r

0    1    2    3    4
0    0.0  0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0  0.0
..   ...  ...  ...  ...  ...
835  0.0  0.0  0.0  0.0  0.0
836  0.0  0.0  0.0  0.0  0.0
837  0.0  0.0  0.0  0.0  0.0
838  0.0  0.0  0.0  0.0  0.0
839  0.0  0.0  0.0  0.0  0.0

[840 rows x 5 columns]

In [24]:
(df_r==df).sum()

0    815
1    822
2    831
3    836
4    840
dtype: int64

False